alias cfb='vim ~/.bash_profile'
alias musApp='cd ~/Desktop/apps/musicianShipDev'
alias VrTimbre='cd ~/Desktop/apps/VrTimbre'
alias connectApps='sh ~/Desktop/connectToApps.command'
#alias syncDotFiles='sh ~/TLLdotfiles/notSynced/scripts/syncDotfiles.sh'
alias gitDotFiles='sh ~/TLLdotfiles/notSynced/scripts/gitScript.sh'
